use QLDETAI
go

/* Q35 */
SELECT MAX(LUONG) AS Luong_Cao_Nhat
FROM GIAOVIEN

/* Q36 */
SELECT *
FROM GIAOVIEN
WHERE LUONG = (SELECT MAX(LUONG) FROM GIAOVIEN)

/* Q37 */
SELECT MAX(LUONG) AS LUONG_CAO_NHAT_HTTT
FROM GIAOVIEN
WHERE MABM = N'HTTT'

/* Q38 */
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE YEAR(GV.NGSINH) = (SELECT MIN(YEAR(NGSINH)) FROM GIAOVIEN GV WHERE GV.MABM IN (SELECT BM.MABM FROM BOMON BM WHERE BM.TENBM = N'Hệ thống thông tin'))

/* Q39 */
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE YEAR(GV.NGSINH) = (SELECT MAX(YEAR(NGSINH)) FROM GIAOVIEN GV WHERE GV.MABM IN (SELECT BM.MABM FROM BOMON BM WHERE BM.MAKHOA IN (SELECT MAKHOA FROM KHOA WHERE TENKHOA = N'Công nghệ thông tin')))

/* Q40 */
SELECT HOTEN, TENKHOA
FROM GIAOVIEN, KHOA, BOMON
WHERE LUONG = (SELECT MAX(LUONG) FROM GIAOVIEN) AND KHOA.MAKHOA = BOMON.MAKHOA AND BOMON.MABM = GIAOVIEN.MABM

/* Q41 */
SELECT *
FROM GIAOVIEN GV
WHERE LUONG >= ALL (SELECT LUONG FROM GIAOVIEN GV2 WHERE GV.MABM = GV2.MABM AND GV.MAGV <> GV2.MAGV)
ORDER BY GV.MABM

/* Q42 */
SELECT TENDT
FROM DETAI
WHERE MADT NOT IN (SELECT MADT FROM THAMGIADT WHERE MAGV IN ( SELECT MAGV FROM GIAOVIEN WHERE HOTEN = N'Nguyễn Hoài An'))

/* Q43 */
SELECT TENDT, HOTEN AS GVCNDT
FROM DETAI, GIAOVIEN
WHERE GIAOVIEN.MAGV = DETAI.GVCNDT AND MADT NOT IN (SELECT MADT FROM THAMGIADT WHERE MAGV IN ( SELECT MAGV FROM GIAOVIEN WHERE HOTEN = N'Nguyễn Hoài An'))

/* Q44 */
SELECT GV.HOTEN
FROM (SELECT HOTEN, MAGV FROM GIAOVIEN WHERE MABM IN (SELECT MABM FROM BOMON WHERE MAKHOA IN (SELECT MAKHOA FROM KHOA WHERE TENKHOA = N'Công nghệ thông tin'))) AS GV
WHERE GV.MAGV NOT IN (SELECT MAGV FROM THAMGIADT)

/* Q45 */
SELECT *
FROM GIAOVIEN
WHERE MAGV NOT IN (SELECT MAGV FROM THAMGIADT)

/* Q46 */
SELECT *
FROM GIAOVIEN
WHERE LUONG > (SELECT LUONG FROM GIAOVIEN WHERE GIAOVIEN.HOTEN = N'Nguyễn Hoài An')

/* Q47 */
SELECT *
FROM GIAOVIEN
WHERE MAGV IN (SELECT TRUONGBM FROM BOMON)
AND MAGV IN (SELECT MAGV FROM THAMGIADT)

/* Q48 */
SELECT *
FROM GIAOVIEN GV1
WHERE EXISTS 
(SELECT * 
FROM GIAOVIEN GV2 
WHERE GV1.HOTEN LIKE GV2.HOTEN
AND GV1.PHAI = GV2.PHAI
AND GV1.MABM = GV2.MABM
AND GV1.MAGV <> GV2.MAGV)

/* Q49 */
SELECT *
FROM GIAOVIEN
WHERE LUONG > ANY (SELECT GV.LUONG FROM GIAOVIEN GV, BOMON BM WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Công nghệ phần mềm')

/* Q50 */
SELECT *
FROM GIAOVIEN
WHERE LUONG > (SELECT MAX(LUONG) FROM GIAOVIEN, BOMON WHERE GIAOVIEN.MABM = BOMON.MABM AND BOMON.TENBM = N'Hệ thống thông tin')

/* Q51 */
SELECT KH.TENKHOA
FROM GIAOVIEN GV, BOMON BM, KHOA KH
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = KH.MAKHOA
GROUP BY KH.MAKHOA, KH.TENKHOA
HAVING COUNT(*) >= ALL(
SELECT COUNT(*)
FROM GIAOVIEN GV, BOMON BM, KHOA KH
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = KH.MAKHOA
GROUP BY KH.MAKHOA)

/* Q52 */
SELECT HOTEN
FROM GIAOVIEN
WHERE GIAOVIEN.MAGV IN
(SELECT GVCNDT
FROM DETAI
GROUP BY GVCNDT
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM DETAI GROUP BY GVCNDT))

/* Q53 */
SELECT MABM
FROM GIAOVIEN
GROUP BY MABM
HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM GIAOVIEN GROUP BY MABM)

/* Q54 */
SELECT HOTEN, TENBM
FROM GIAOVIEN GV, BOMON BM
WHERE BM.MABM = GV.MABM AND GV.MAGV IN 
(SELECT MAGV
FROM THAMGIADT
GROUP BY MAGV
HAVING COUNT(DISTINCT MADT) >= ALL (SELECT COUNT (DISTINCT MADT) FROM THAMGIADT GROUP BY MAGV))

/* Q55 */
SELECT HOTEN
FROM GIAOVIEN GV, THAMGIADT DT
WHERE GV.MAGV = DT.MAGV AND GV.MABM = N'HTTT'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) >= ALL(SELECT COUNT(DISTINCT THAMGIADT.MADT) FROM THAMGIADT WHERE GV.MAGV = THAMGIADT.MAGV GROUP BY THAMGIADT.MAGV)

/* Q56 */
SELECT *
FROM GIAOVIEN
WHERE MAGV IN
(SELECT MAGV
FROM NGUOITHAN
GROUP BY MAGV
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM NGUOITHAN GROUP BY MAGV))

/* Q57 */
SELECT HOTEN
FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM AND GIAOVIEN.MAGV IN
(SELECT GVCNDT
FROM DETAI
GROUP BY GVCNDT
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM DETAI GROUP BY GVCNDT))